<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findAllOrderedByID()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Category p ORDER BY p.id ASC'
            )
            ->getResult();
    }

    public function moveCategory($category_id, $old_parent_id, $new_parent_id){
        $category = $this->find($category_id);
        $old_parent = $this->find($old_parent_id);
        $new_parent = $this->find($new_parent_id);
        $category->setParent($new_parent);
        $this->getEntityManager()->merge($category);
        $this->getEntityManager()->flush();
    }
}
